### ISSUE TITLE
Effects not working in Android 10 (in pie it's working flawlessly) redmi k20 

### ISSUE THREAD

**Issue by vinod9866** [Pittvandewitt/Wavelet#72] opened 2021-05-05 18:22 UTC
In redmi k20 it's working excellent on pie only, when I update to Android 10 , only Equalizer some what working... Bass booster etc reducing volume 50% and not working..!

**Comment by Pittvandewitt** [comment] 2021-05-09 21:50
Unfortunately the bass booster library got changed during the Android 10 update. It is caused by [one of these commits](https://android.googlesource.com/platform/frameworks/av/+log/master/media/libeffects/lvm/lib/Bass).
I am planning to replace it with a wider frequency range for the bass tuner on Android 10 and up.

In an attempt to reduce audio latency, a few flags may have been enabled on your device with the update, causing some features not to work in legacy mode. Please disable legacy mode to resolve potential issues. In case you struggle getting default mode to work, please check out [donktkillmyapp](https://dontkillmyapp.com/xiaomi)

It would be appreciated if you could send an email as reply instead of using the issues here, as you are asking for support and I am certain the issue can be resolved by setting up your device and Wavelet correctly. You can find my email address in my Github profile description.

**Closed by Pittvandewitt** 2021-05-09 21:50 UTC

**Comment by vinod9866** [comment] 2021-05-13 12:56
Sir, I've sent you the mail on elaboration of problem.
