### ISSUE TITLE
Auto EQ Does not show up in chrome OS

### ISSUE THREAD

**Issue by theportal2** [Pittvandewitt/Wavelet#68] opened 2021-04-11 23:25 UTC
My Sony Wl-C200 does not have auto EQ in the app on my chrome OS device but it does on my pixel 4a 5g.

**Comment by Granshmeyr** [comment] 2021-04-26 05:37
I have the same issue. Wavelet does not display the menu for Headset settings, nor does the notifcation update to "Headset connected" upon plugging in a **3-pole (no microphone)** headset. However, plugging in a **4-pole (with microphone)** headset allows for proper detection of the headset. I don't have a bluetooth headset to test that though.

To clarify, this issue is caused by the Android subsystem in ChromeOS, _not_ Wavelet. Plugging in a 3-pole headset doesn't actually register a new device and the output device remains as `SNK Type: 2/TYPE_BUILTIN_SPEAKER`. However, plugging in a 4-pole headset registers a new device as `SNK Type: 3/TYPE_WIRED_HEADSET`. In addition, it seems like the `android.intent.action.HEADSET_PLUG` broadcast is not sent when plugging in a 3-pole headset either. I verified all of this using the Debug / Event Log outputs of [Lesser AudioSwitch](https://play.google.com/store/apps/details?id=com.nordskog.LesserAudioSwitch).

 

There is a workaround. If you open [Lesser AudioSwitch](https://play.google.com/store/apps/details?id=com.nordskog.LesserAudioSwitch) and set the HEADPHONES output to explicitly utilize "Headset microphone", you can then swap to the HEADPHONES output which sets `♪ Output: Headset` whereas it would not set before. It seems like this essentially emulates plugging in a 4-pole headset rather than a 3-pole headset. This allows you to register the `SNK Type: 3/TYPE_WIRED_HEADSET` device with or without plugging in a headset and Wavelet will switch to Headset mode (allowing you to use AutoEQ).

If you use this solution you will have to manually swap to the HEADPHONES output in  [Lesser AudioSwitch](https://play.google.com/store/apps/details?id=com.nordskog.LesserAudioSwitch) every time you boot into ChromeOS. Or you could pay for the app and use the restore on boot feature to swap to it automatically if you are rich. By the way, it doesn't actually matter if the app sets `♪ Output: Headset` even if you want to use the Chromebook's built-in speaker as the audio will still play from the speaker as long as no headset is plugged in.

A word of warning: when using AutoEQ or the Graphic equalizer on ChromeOS it seems like the audio will clip even with "Reduce clipping" enabled. I recommend you simply disable it for better latency, then go to "Channel balance" and set a preamp equal to the largest preamp value for your headphone in the AutoEQ GitHub or just set it to -9.9dB.

 

I guess it's not possible to "fix" this within Wavelet other than allowing access to the Headset menu regardless of whether a Headset is actually plugged in or not, because the app cannot tell.

**Comment by Pittvandewitt** [comment] 2021-05-09 21:26
@Granshmeyr Thank you very much for the valuable information provided. The information you provide about the headset detection confirms my assumption that Wavelet is not being informed about headphones connecting by the OS.
Because the application does not seem to work on Android 11 and up and the danger of its functionality being overused, it may not be a good idea to provide the functionality in Wavelet natively. However I do believe it is a good option to update the troubleshooting page with the suggestion to install the application you mention on ChromeOS devices.

The issue regarding clipping is probably because an early version of the dynamicsprocessing in being used. Android 9 had similar issues which could be minimized by enabling clipping reduction. I am planning to expand on the clipping reduction option to allow for finer control.

I am closing the issue because the problem is caused by the Android subsystem, though further discussion is encouraged.

**Closed by Pittvandewitt** 2021-05-09 21:26 UTC
