### ISSUE TITLE
Issue if app is deleted while wavelet is equalising it

### ISSUE THREAD

**Issue by Netherquark** [Pittvandewitt/Wavelet#125] opened 2021-12-02 07:53 UTC
I saw AIMP showing up as a media source in wavelet and deleted the app because I dont use AIMP anymore. However this is staying: 

![Screenshot_20211202-132111298 (1).jpg](https://user-images.githubusercontent.com/65618735/144380249-ccae6851-b92b-4da1-bb55-0abd2ceb2e34.jpg)

Also wavelet doesnt use Bluetooth device nicknames, but instead uses the actual device name. Would be cool if it could show "netherquark's earphones" instead of "rockerz 330" if that is saved as the nickname in settings

**Comment by Pittvandewitt** [comment] 2022-01-02 14:43
Thank you for sharing your input.
The first issue is caused by the session of the removed app not being closed properly. This can only be resolved by having a service running all the time to watch changes in package installation. In my opinion the drawback of this would be much more significant then having the null item in the title. If you reboot your device, all sessions (including the one triggering the null value) will be flushed anyway.

Getting the user defined Bluetooth name would require to ask for Bluetooth permission: https://developer.android.com/reference/android/bluetooth/BluetoothAdapter#getName()
If that was not the case I would have considered displaying the user defined title.

**Closed by Pittvandewitt** 2022-01-02 14:43 UTC
