### ISSUE TITLE
Volume drops shortly on volume changes

### ISSUE THREAD

**Issue by tarsonis123** [Pittvandewitt/Wavelet#320] opened 2024-10-26 14:17 UTC
Hello,

Using Realme OS with Poweramp and Wavlet AutoEQ+Custom EQ target in legacy mode. When I change the system volume the loudness drops significantly for a second before it reaches the desired volume setting. This is happening with wired headsets, with different buffer settings and YT or Tidal. I was not able to check if the Non-Legacy Mode behaves the same yet. What can be the issue here?

RMX3393_14.0.0.1000
ColorOS 14
Kernel 4.19.191+

**Comment by Pittvandewitt** [comment] 2024-10-27 16:26
Starting from which version or day of update did you notice this issue? What device are you using?

**Comment by tarsonis123** [comment] 2024-10-27 17:01
It's a Realme 9 pro plus. Unfortunately I have this issue since I discovered Wavlet a few months ago. What I found out is that disabling Direct

**Comment by Pittvandewitt** [comment] 2024-11-10 17:35
Can you confirm if the issue is resolved in version 24.11?

**Closed** 2024-11-21 10:14 UTC
