### ISSUE TITLE
Add notification button

### ISSUE THREAD

**Issue by Incognito009** [Pittvandewitt/Wavelet#240] opened 2023-04-06 05:10 UTC
![Screenshot_20230406_103101_One UI Home](https://user-images.githubusercontent.com/76397211/230277078-d54a3b7e-2b0c-4d1d-93e4-640a64be1ecd.jpg)
Add notifications button like above  given img.

**Comment by Pittvandewitt** [comment] 2023-07-01 12:48
Duplicate of https://github.com/Pittvandewitt/Wavelet/issues/225

**Closed by Pittvandewitt** 2023-07-01 12:48 UTC
