### ISSUE TITLE
Unable to instantiate toast message

### ISSUE THREAD

**Issue by harrickeyh** [Pittvandewitt/Wavelet#155] opened 2022-02-18 04:53 UTC
Hi, everytime I launch wavelet it prompts the following message, both in legacy / non legacy mode, i even paid for the upgrade. 
![Screenshot_20220218_125100_com pittvandewitt wavelet](https://user-images.githubusercontent.com/63963428/154619829-7ef780b2-dd23-4bb6-bcc8-61b800793bca.jpg)
I'm using youtube music and or spotify if that makes a difference.
Also my wavelet started to not launch automatically, despite both settings being enabled. It was working fine 1-2months before

**Comment by Pittvandewitt** [comment] 2022-02-18 13:14
duplicate of #143

**Closed by Pittvandewitt** 2022-02-18 13:14 UTC
