### ISSUE TITLE
License Transfer to new device

### ISSUE THREAD

**Issue by the-moosen** [Pittvandewitt/Wavelet#327] opened 2024-11-15 16:28 UTC
I read through the troubleshooting & tried restarting, reinstalling, etc. For whatever reason the license did not/will not transfer over from my Pixel 7 to my Pixel 9 Pro. The app will not give me the option for buffer size, reverb, visualization, bass tuner. I don't know if it's because I'm on Android 15 on the 9P.

**Comment by PaulTran47** [comment] 2024-11-19 08:10
Adding a comment about also experiencing this issue. I made the purchase to unlock all of wavelet's features back in 2020. When transferring over from my Pixel 6 Pro to my Pixel 9 Pro, I noticed that the license/unlock purchase didn't transfer over. I no longer have the option to change the buffer size and any of the other features.

I've tried to uninstall wavelet, leave and re-join the beta programme, restart the device, clear the cache and storage of the Play Store, open wavelet through the Play Store, and it seems my purchase isn't able to be linked to my Pixel 9 Pro download.

As a related test, I deleted wavelet from my Pixel 7 Pro and reinstalled the app. It looks like the purchase is "remembered" on the Pixel 7 Pro since I could see all of the unlocked features on the device. But no dice on my new device...

**Comment by Pittvandewitt** [comment] 2024-11-21 10:10
It's not an issue with the licence. It was transferred correctly. The issue is that Google shipped broken software with the Pixel 9 in which the features you are missing are broken on the device. Google is aware about the issues they introduced. Sorry but I can't fix the mess they created.

**Closed by Pittvandewitt** 2024-11-21 10:10 UTC
