### ISSUE TITLE
Wavelet was unable to instantiate Insert Presset Reverb Pixel 7

### ISSUE THREAD

**Issue by Nester0v** [Pittvandewitt/Wavelet#242] opened 2023-04-11 22:46 UTC
![Screenshot_20230412-003653](https://user-images.githubusercontent.com/89090560/231303941-986eef10-83d1-4ad9-8c79-3d8a2c192fa7.png)

Hello, guys! Have the next problem: Wavelet was unable to instantiate Insert Presset Reverb....

Phone - Google Pixel 7
Headphones - Samsung Galaxy Buds Live

All sound improvements, eq etc. I have turned off.
Full Version was bought.
Problem fixing only by app reinstalling, and helps only for two days, after two days problem come back. Maybe someone faced with this problem too...

**Comment by Pittvandewitt** [comment] 2023-07-26 10:53
Duplicate of https://github.com/Pittvandewitt/Wavelet/issues/231

**Closed by Pittvandewitt** 2023-07-26 10:53 UTC
