### ISSUE TITLE
Premium account not recognized

### ISSUE THREAD

**Issue by SKR-974** [Pittvandewitt/Wavelet#81] opened 2021-06-15 15:18 UTC
Hello,
My premium account is not recognized,
The app asks me to pay again,
Can you help me please ?

**Comment by Pittvandewitt** [comment] 2021-06-20 21:43
Your payment provider probably did not complete the transaction yet. If this is the case, it is out of my control.
If you received an order ID from Google [https://support.google.com/store/answer/6160235](https://support.google.com/store/answer/6160235), I can help you further, but not here publicly. Sending me an email would be the right way.

**Comment by Pittvandewitt** [comment] 2021-07-15 13:37
Some issues regarding payments are resolved in the version available in the beta track. The beta track can be joined via the Play Store listing. Feel free to reopen if you feel the issue is not resolved.

**Closed by Pittvandewitt** 2021-07-15 13:37 UTC
