### ISSUE TITLE
QuickSettings tile to toggle EQ

### ISSUE THREAD

**Issue by Netherquark** [Pittvandewitt/Wavelet#175] opened 2022-05-31 07:19 UTC
A QS tile to toggle EQ would greatly improve convenience while listening to music

**Comment by Akusimr** [comment] 2022-05-31 07:25
@ # #165

**Comment by Akusimr** [comment] 2022-05-31 07:25
Duplicate of #

**Comment by Netherquark** [comment] 2022-05-31 07:26
my bad

**Comment by Akusimr** [comment] 2022-05-31 07:26
[https://github.com/Pittvandewitt/Wavelet/issues/175#issue-1253436730]()

**Comment by Pittvandewitt** [comment] 2023-12-12 12:43
Implemented in version 23.12

**Closed by Pittvandewitt** 2023-12-12 12:43 UTC
